function [H,Sz]=main(h,dphy,D,Dcut)
[T,lx,ly,lz]=initialstates(dphy,D);
%% evolution;
%{
time=1000;
[T,lx,ly,lz]=update(T,lx,ly,lz,h,dphy,D,0.5,time);
[T,lx,ly,lz]=update(T,lx,ly,lz,h,dphy,D,0.2,time);
[T,lx,ly,lz]=update(T,lx,ly,lz,h,dphy,D,0.1,time);
[T,lx,ly,lz]=update(T,lx,ly,lz,h,dphy,D,0.05,time);
[T,lx,ly,lz]=update(T,lx,ly,lz,h,dphy,D,0.02,time);
[T,lx,ly,lz]=update(T,lx,ly,lz,h,dphy,D,0.01,time);
[T,lx,ly,lz]=update(T,lx,ly,lz,h,dphy,D,0.005,time);
[T,lx,ly,lz]=update(T,lx,ly,lz,h,dphy,D,0.002,time);
[T,lx,ly,lz]=update(T,lx,ly,lz,h,dphy,D,0.001,time);
[T,lx,ly,lz]=update(T,lx,ly,lz,h,dphy,D,0.0005,time);
[T,lx,ly,lz]=update(T,lx,ly,lz,h,dphy,D,0.0002,time);
[T,lx,ly,lz]=update(T,lx,ly,lz,h,dphy,D,0.0001,time);
%}
%%
[K,T]=absorb(T,lx,ly,lz,D);
%[Upx,Dnx,Lx,Rx]=environmentx(K,Dcut,D);
%[Upy,Dny,Ly,Ry]=environmenty(K,Dcut,D);
[Upz,Dnz,Lz,Rz]=environmentz(K,Dcut,D);
%%
sigmax=[0,1;1,0];
sigmaz=[1,0;0,-1];
identi=[1,0;0,1];

Sx1=bondz(Upz{1},Dnz{1},Lz{1},Rz{1},T{4},T{1},sigmax,identi,D);
Sx2=bondz(Upz{2},Dnz{2},Lz{2},Rz{2},T{2},T{3},sigmax,identi,D);
Sx3=bondz(Upz{3},Dnz{3},Lz{3},Rz{3},T{6},T{5},sigmax,identi,D);
Sx4=bondz(Upz{1},Dnz{1},Lz{1},Rz{1},T{4},T{1},identi,sigmax,D);
Sx5=bondz(Upz{2},Dnz{2},Lz{2},Rz{2},T{2},T{3},identi,sigmax,D);
Sx6=bondz(Upz{3},Dnz{3},Lz{3},Rz{3},T{6},T{5},identi,sigmax,D);
Sx=(Sx1+Sx2+Sx3+Sx4+Sx5+Sx6)/6;
SzSz1=bondz(Upz{1},Dnz{1},Lz{1},Rz{1},T{4},T{1},sigmaz,sigmaz,D);
SzSz2=bondz(Upz{2},Dnz{2},Lz{2},Rz{2},T{2},T{3},sigmaz,sigmaz,D);
SzSz3=bondz(Upz{3},Dnz{3},Lz{3},Rz{3},T{6},T{5},sigmaz,sigmaz,D);
SzSz=(SzSz1+SzSz2+SzSz3)/3;
H=-SzSz-h*2/3*Sx;

Sz1=bondz(Upz{1},Dnz{1},Lz{1},Rz{1},T{4},T{1},sigmaz,identi,D);
Sz2=bondz(Upz{2},Dnz{2},Lz{2},Rz{2},T{2},T{3},sigmaz,identi,D);
Sz3=bondz(Upz{3},Dnz{3},Lz{3},Rz{3},T{6},T{5},sigmaz,identi,D);
Sz4=bondz(Upz{1},Dnz{1},Lz{1},Rz{1},T{4},T{1},identi,sigmaz,D);
Sz5=bondz(Upz{2},Dnz{2},Lz{2},Rz{2},T{2},T{3},identi,sigmaz,D);
Sz6=bondz(Upz{3},Dnz{3},Lz{3},Rz{3},T{6},T{5},identi,sigmaz,D);
Sz=(Sz1+Sz2+Sz3+Sz4+Sz5+Sz6)/6;
Sz=abs(Sz);
end